### ISSUE TITLE
How to save the generated faces?

### ISSUE THREAD

**Issue by sivaramakrishnan-rajaraman** [Hzaeaekk/FaceGenKerasVae#1]
Can you please let know how to store the generated faces (say a sample of 10000 images) to a separate folder?

**Comment by Hzaakk** [comment]
If you have the images array in the RGB format stored in a 4d array shaped like (number_of_images, Y, X, 3), then you can make a folder for images and do
```
for idx, image in enumerate(images):
     plt.imsave(f'image_folder/image_{idx}.png', image)
```

If they're in the BGR format, you can use `cv2.imwrite` instead of `plt.imsave` using the same arguments of a filename and a 3-dimensional numpy array.
Otherwise, u can make the images in the for loop itself; You just have to make sure they have the shape (Y, X, 3).
